Removes broken powergamer quirk that was snuck into the code.
Skyrat-SS13/Skyrat13 pull request #3350
Opened 2020-08-11 04:48 UTC by KathrinBailey

## About The Pull Request
• Paper skin quirk removed.

## Why It's Good For The Game
This shit doesn't even work.
I'm sorry but three quirks points for taking 16.5 damage from a welder instead of 15? Three points for taking 66 damage from a 7.62 bullet instead of 60?
What gets you three quirk points?
A fucking brain tumor.
Not having functional fucking legs.
Do you know what you get for two points?
Being mute.

Am I honestly supposed to believe that taking 10% more damage is an equal downside to not having working legs? It's not even equal to being mute, even with paper and text to speech devices. 

Sneaking powergamer shit like this in is a new low and I'm honestly fucking disgusted by it. This is good for the game because having three quirk points with no downsides is bad for the gamer and this is stopping that.

## Changelog
:cl:
del: paper skin quirk
/:cl:

## Media
![image](https://user-images.githubusercontent.com/53862927/89858032-81a67000-db95-11ea-88af-293d42ef1399.png)
This doesn't even work when you have melee armour.

2020-08-11 04:49 UTC, ShadeAware commented
Wouldn't it be better to try and actually... fix and rebalance it instead of just pulling an 🍊 and removing the content in a hissy fit?

2020-08-11 05:21 UTC, BobJoga commented
Just lower the costs Kat. Are you serious?

2020-08-11 05:49 UTC, Owai-Seek commented
Could make it a neutral quirk to see how many people dump it.

2020-08-11 07:05 UTC, SpaceVampire commented
I think the best way to handle it is just making the trait more deadly. 50% more damage or bust.

2020-08-11 08:56 UTC, CameronWoof commented
Good PR. Disappointed by the disrespectful comments here.

2020-08-11 17:34 UTC, hugmeorelse commented
> Good PR. Disappointed by the disrespectful comments here.

I hope you also meant the PR description there as well. Neither are great.

> Wouldn't it be better to try and actually... fix and rebalance it instead of just pulling an 🍊 and removing the content?
> 
> **Note by Staff:** Keep it civil.

I removed the passive-aggressive remark. Next time, I'll remove your entire comment, just like I did with the PR description.

> Just lower the costs Kat. Are you serious?

They were talked to, however, please avoid starting fights.

2020-08-11 17:37 UTC, hugmeorelse commented
> Good PR. Disappointed by the disrespectful comments here.

I hope you also meant the PR description there as well. Neither are great.

> Wouldn't it be better to try and actually... fix and rebalance it instead of just pulling an 🍊 and removing the content?
> 
> **Note by Staff:** Keep it civil.

I removed the passive-aggressive remark. Next time, I'll remove your entire comment, just like I did with the PR description. Just because the PR description is rude doesn't mean you have to be here on Github.

> Just lower the costs Kat. Are you serious?

They were talked to, however, please avoid starting fights. If you have an issue, report it to another maintainer or the head maintainers like Azarak and Useroth. Do not instigate a fight.

> Could make it a neutral quirk to see how many people dump it.

Don't popcorn/peanut post if you don't have anything pertinent to say about the PR itself.

2020-08-11 17:38 UTC, hugmeorelse commented
> I think the best way to handle it is just making the trait more deadly. 50% more damage or bust. Could also make it reduce your max health as well.

Thanks for providing a helpful critique without being toxic. It's much appreciated

> Good PR. Disappointed by the disrespectful comments here.

Agreed, but I also hope you also meant the PR description there as well. Neither are great.

> Wouldn't it be better to try and actually... fix and rebalance it instead of just pulling an 🍊 and removing the content?
> 
> **Note by Staff:** Keep it civil.

I removed the passive-aggressive remark. Next time, I'll remove your entire comment, just like I did with the PR description. Just because the PR description is rude doesn't mean you have to be here on Github.

> Just lower the costs Kat. Are you serious?

They were talked to, however, please avoid starting fights. If you have an issue, report it to another maintainer or the head maintainers like Azarak and Useroth. Do not instigate a fight.

> Could make it a neutral quirk to see how many people dump it.

Don't popcorn/peanut post if you don't have anything pertinent to say about the PR itself.

2020-08-11 20:11 UTC, Owai-Seek commented
It is pertinent to the PR, it's a suggestion to make it neutral in terms of points instead of complete removal. It'd be more of a flavor quirk, but would remain for people who want it.

2020-08-11 22:25 UTC, hugmeorelse commented
> It is pertinent to the PR, it's a suggestion to make it neutral in terms of points instead of complete removal. It'd be more of a flavor quirk, but would remain for people who want it. (Even if armor overrides it, it would still show up on medical scans to basically say "This person is fragile.")

"Could make it a neutral quirk **to see how many people dump it.**"

Second half makes it seem like you were doing it to mock folks. Tone is difficult to tell. This post you made is much better. Make more of these, and I'll be happy.

2020-08-12 09:18 UTC, Commandersand commented
just give it increased chances of bobmed injuries happening, i think that's worth 3 points of having a chance to go to medbay just for misclicking on a lightbulb or something

2020-08-12 20:42 UTC, chefferz commented
Please test all types of weaponry instead of a simple screwdriver stab, and compare them. Paper skin can make fights quite miserable.

2020-08-24 18:31 UTC, BobJoga commented
So, with #2578, i've reworked this quirk to cause more slash and puncture injuries, and i've changed it to give you 2 points instead. I feel it's a fair enough quirk now.

2020-09-11 09:41 UTC, Akrilla requested changes
Needs addressing, likely a close.

2020-09-26 00:30 UTC, closed without merging