[Bagatji drink recipe] There's a Snake in my Bar
Skyrat-SS13/Skyrat13 pull request #3440
Opened 2020-08-19 16:18 UTC by NotRanged

## About The Pull Request

Made on request of Xyverious.

Adds Bagatji wine (5 wine, 2 toxin, 3 mindbreaker). On consumption, it does toxins, staminaloss and makes you hallucinate for a while. Characters with naga bodies are immune to these effects.

## Why It's Good For The Game

Snek wine!

## Changelog
:cl:
add: Added drink recipe 'Bagatji Wine'. Made with 5u wine, 2u toxin, 3u mindbreaker. Result is 5u. Consumption by non-Bagatji is not recommended.
/:cl:

2020-08-19 16:53 UTC, CameronWoof commented
Xyverious is cool but adding custom stuff for a race you made up is pretty lame. Also, 50 tox damage per sip is pretty silly.

2020-08-19 18:25 UTC, NotRanged commented
50 toxin per sip spread out over more than 2 minutes. 0.4 tox per second would take any minutes to kill, if you can't find antitox in that time it's on you tbh

2020-08-19 18:39 UTC, CameronWoof commented
I just generally feel like this is content with such a narrow audience that it feels bad on principle. It feels like codifying a sort of special snake club by giving them content that only they can safely enjoy. The fact that it's named after someone's OC race makes it feel like that special lavaland dragon thing all over again.

2020-08-19 21:39 UTC, NotRanged commented
Numbers changed. 5u now does 39 toxin damage over a 25 second period.

2020-08-19 21:42 UTC, Echopsychotic commented
just be a slime and enjoy the drink

2020-08-20 04:26 UTC, KathrinBailey commented
![image](https://user-images.githubusercontent.com/53862927/90716780-a2fa1100-e2a5-11ea-8894-3a3bd7e3033b.png)

2020-08-26 13:12 UTC, KathrinBailey requested changes
You just need to lower the toxin damage a tiny bit.

2020-08-26 13:12 UTC, KathrinBailey commented on modular_skyrat/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +		H.adjustToxLoss(3*REM) // Bagatji (and all snake taurs) take no ill effects.
Everything but this is okay. It's currently 39 toxin damage per single sip, given the not super hard to obtain crafting recipe it probably should be lowered just a tad.
Lowering this to 2.5 will deal 32.5 toxin damage per sip.
Lowering this to 2 will deal 26 toxin damage per sip.

Change to either 2 or 2.5 and ping me at Floof Ball#0798 once done and once I'm able I'll merge it. I can quickly do it for you if you also ping me to say it's okay.

2020-08-26 14:17 UTC, KathrinBailey approved these changes

2020-08-26 14:28 UTC, merged