[CURRENTLY AFFECTS NOTHING] Reworks rewind camera
Skyrat-SS13/Skyrat13 pull request #3478
Opened 2020-08-28 17:37 UTC by dankmemerino147

virgin sepia extract vs chad most other extracts

## About The Pull Request

Reworks the rewind camera. It can now be reused, on a 2 minute cooldown (1 min for chars with photographer trait), but the second rewind for each use is gone to compensate, and the camera requires a film cartridge reload for each use.

Currently, photography is disabled; this means film cartridge reloads don't work. The effect of this is that this PR changes very little about how the camera factually operates; the second rewind is removed, making this actually be a slight nerf until photography is re-enabled.

## Why It's Good For The Game

Sepia extracts are hard to obtain, and basically worth nothing in their current state. The only use of them that I would consider worthwhile is for the chilling crossbreed, and even that is mediocre; the user can't be immune to the timestop (although others can), and it's a single-use item that's very difficult to obtain. 

Contrast this with something like bluespace extracts, which are at the same level of difficulty to obtain - but you don't even have to crossbreed them to get the incredibly-useful, to the point of lining at least Central Primary when made, bluespace floor tiles; or industrial extracts, which give you an _infinite source_ of select items - ranging from food and drinks, to fireproofing potions, to regen jelly autoinjectors(!), to synthpax autoinjectors(!!) - with very little (1 plasma sheet) investment cost, assuming you get your hands on an industrial dark purple. These things aren't bad for the game, xenobio is meant to be powerful; sepias, though, just aren't.

This change makes sepia extracts more worthwhile in the long term - the rewind camera becomes a multi-use item with a powerful effect, balanced with a long cooldown and a fuel requirement.

## Changelog
:cl:
balance: Rewind camera can now be reused, on a 2 minute cooldown to which the Photographer trait applies; film cartridge reload required, and second rewind per use is removed. (NO TYPE OF CAMERA CAN BE RELOADED UNTIL PHOTOGRAPHY IS RE-ENABLED, making this an effective nerf until then)
/:cl:

2020-08-29 22:48 UTC, Gandalf2k15 requested changes

2020-08-29 22:48 UTC, Gandalf2k15 commented on modular_skyrat/code/modules/research/xenobiology/crossbreeding/burning.dm
> +	.=..()
aaaa newline pls

2020-08-30 00:46 UTC, dankmemerino147 commented on modular_skyrat/code/modules/research/xenobiology/crossbreeding/burning.dm
> +	.=..()
ight

2020-09-13 03:01 UTC, Gandalf2k15 approved these changes

2020-09-13 03:03 UTC, merged