Adds a some fun adminbus gear, the Solar Armor and Daybreak
Skyrat-SS13/Skyrat13 pull request #3480
Opened 2020-08-29 02:36 UTC by ShadeAware

## About The Pull Request
Adds the Solar Armor, an absolutely OP 90 melee/bullet/fire resistant armor set. Also adds the Daybreak, a spear-like weapon which deals 50 damage on normal attack and 150 on throw.

**Both of these items are adminspawn only.**

## Why It's Good For The Game
Funny Terraria references, fun Admin stuff.

## Changelog
:cl:
add: Solar Armor for Adminbus
add: Daybreak spear weapon for Adminbus
/:cl:

2020-08-29 14:12 UTC, H0gberg commented
I will be using this to admin bus these dum tators, very cool mike

2020-08-29 22:29 UTC, Gandalf2k15 requested changes

2020-08-29 22:29 UTC, Gandalf2k15 commented on modular_skyrat/code/game/objects/items/weaponry.dm
> +	w_class = WEIGHT_CLASS_BULKY
Aaaah, newline pls

2020-08-29 22:29 UTC, Gandalf2k15 commented on modular_skyrat/code/modules/clothing/suits/armor.dm
> +	equip_delay_other = 60
Newline here too plssss

2020-08-30 20:26 UTC, ShadeAware commented
Ill work more on this later, I just can't be assed to fix the conflicts right now with all of the projects I have going on

2020-09-26 02:43 UTC, closed without merging