I don't want to ride my bike
Skyrat-SS13/Skyrat13 pull request #3508
Opened 2020-09-03 17:43 UTC by BobJoga

## About The Pull Request

Comments out the bicycle crate. It was way too easy to get with exploits, mostly wishgranter related, and it's just awful to deal with.

## Why It's Good For The Game

Already said everything.

## Changelog
:cl:
del: Removed bicycle crate from cargo. Freddy Mercury is disappointed.
/:cl:

2020-09-03 17:45 UTC, RatFromTheJungle commented
@BobJoga replace with a loot crate

2020-09-03 17:46 UTC, RatFromTheJungle requested changes
Replace with a loot crate

2020-09-06 02:56 UTC, YakumoChen commented
I kind of don't see the value of nerfing it. It costs literally a million credits.

2020-09-06 17:20 UTC, H0gberg commented
to be fair milions of credits means nothing to cargo, you could straight up just work with atmos and make it in minutes into the shift, the speed of it was completely broken and somewhat annoying

2020-09-08 21:32 UTC, YakumoChen commented
Sounds like a better case for nerfing atmos than nerfing the obscenely expensive item

2020-09-10 18:39 UTC, ForrestWick commented
The bicycle was apparently made to incentive people to find cargo bugs and "exploits" that could result in serious credit cheesing so that people could report them and fix them.

2020-09-12 08:34 UTC, Tename commented
The few times I saw it, the speed it moves was so bad due to normal server performance it just teleported around and was 100% impossible to catch someone on it without bolting every door and shutting every firelock in 20 miles.

2020-09-12 08:37 UTC, ForrestWick commented
> The few times I saw it, the speed it moves was so bad due to normal server performance it just teleported around and was 100% impossible to catch someone on it without bolting every door and shutting every firelock in 20 miles.

That's the point. It's an incredibly unique item that is normally extremely hard to obtain if you aren't savvy or looking for cargo related bugs. It's supposed to be a reward for those that are intuitive or a goal for those looking to find cargo exploits. It's so rare that dealing with someone getting it is a non issue

2020-09-12 09:00 UTC, Tename commented
> 
> 
> > The few times I saw it, the speed it moves was so bad due to normal server performance it just teleported around and was 100% impossible to catch someone on it without bolting every door and shutting every firelock in 20 miles.
> 
> That's the point. It's an incredibly unique item that is normally extremely hard to obtain if you aren't savvy or looking for cargo related bugs. It's supposed to be a reward for those that are intuitive or a goal for those looking to find cargo exploits. It's so rare that dealing with someone getting it is a non issue

Well it still mostly abuses the fact the games performance isn't up to par with its speeds, and I am not like a fan of that.

2020-09-12 20:17 UTC, YakumoChen commented
The bike is only a symptom of a cargo problem every time its bought. If it weren't a hilariously powerful joke item it would be harder to notice or justify cargo balancing.

2020-10-11 00:35 UTC, closed without merging