Removes die of fate from xenoarch
Skyrat-SS13/Skyrat13 pull request #3554
Opened 2020-09-13 13:37 UTC by IrkallaEpsilon

Nope

## About The Pull Request

Call it "No fun allowed". It happened far too often the past couple days. People throw the dice making it essentially not disappear and multi use. Since that is still an issue on TG and theres no fix I could simply try and port over we go by removing this thing from the loot table. People keep trying to roll for wizard while naked and having a syringe to remove monkeyfication on it while having a backup clone. Wizard is ultra rare for a reason. 

## Why It's Good For The Game

The fact that the die of fate is multi use when thrown instead of used in hand is bad. This removes the dreaded thing from loot tables. 

Other options I considered: Go on and comment out every 'bullshit' spell wizards possess. 

## Changelog
:cl:
del: Die of fate xenoarch loot.
/:cl:

2020-09-13 13:45 UTC, ShadeAware commented
Just make it single use ffs

2020-09-13 14:06 UTC, MLGTASTICa commented
just make it one use

2020-09-13 14:58 UTC, ThatGuyFromThatPlace commented
I've witnessed the LRP and stupidity the dice causes. Everyone throwing it taking turns as if it doesn't have a chance to kill them, possibly dusting them, or, in the case of the previous example I saw, killing themselves and several bystanders thanks to a creature swarm around others

2020-09-13 21:14 UTC, SarmentiCampbell requested changes
Don't be dumb and just get the one use dice instead of straight up removing it.
/obj/item/dice/d20/fate/one_use

2020-09-15 21:35 UTC, SpaceVampire commented
Yeah I agree with everyone else, just make it single use.

2020-09-16 01:55 UTC, Azarak requested changes

2020-09-16 01:55 UTC, Azarak commented on modular_skyrat/code/modules/research/xenoarch/artifact_list.dm
>  									/obj/item/pen/edagger=1,
```suggestion
									/obj/item/pen/edagger=1,
									/obj/item/dice/d20/fate/one_use=1,
```

2020-09-16 01:55 UTC, Azarak commented on modular_skyrat/code/modules/research/xenoarch/artifact_list.dm
>  									/obj/item/pen/edagger=1,
One use should be fine

2020-10-29 00:39 UTC, closed without merging