[WIP] Export buff revival
Skyrat-SS13/Skyrat13 pull request #3573
Opened 2020-09-17 13:10 UTC by Investigator77

## About The Pull Request

IT'S BACK BABY

This PR increases a lot of low prices and makes cargo exports more profitable, as to break the crypto and glassworking meta and make the job fun again.

It also changes some bounties and descriptions to be more lore-friendly.

## Why It's Good For The Game

Our cargo system (Citadel Code) has been relentlessly nerfed to no end, while all other departments receive buffs. This results in every job being able to complete their shit one hour into the shift, except cargo though! Unless you abuse glassworking or crypto, you'll be stuck in under a hundred thousand for the entire shift if anyone buys anything!

## Changelog
:cl:
tweak: Buffed weapon and equipment exports
tweak: Buffed a lot of science bounties
tweak: Buffed reagent bounties
tweak: Changed heart from 3k > 5k
tweak: Changed Adamantine, Documents and Xeno Organ bounties back to pre-nerf value.
tweak: Made material values make more sense.
tweak: Statues are now more expensive.
tweak: REVIEW TWEAK: 4.6x30mm mag 500 > 100 / 4.6x30mm [IN/AP/TX] mag 550 > 150
tweak: Parts are now more expensive, and so are cells.
tweak: Medical research (Robotic organs, limbs) has slightly higher export values.
tweak: Mech weapons and equipment have slightly higher export values.
tweak: Buffed tool exports.
tweak: Changed some descriptions for bounties
/:cl:

2020-09-17 13:44 UTC, Investigator77 commented
After a price bump to reagents it should be ready to go.

2020-09-17 21:57 UTC, Investigator77 commented
We're good to go.

2020-09-18 04:05 UTC, Owai-Seek commented
I don't know why people feel the need to have enough money to unlock a bicycle every round when cargo has perfectly viable ways to make cash. I do wish for the bounty system to be fleshed out, because bounties are honestly -not worth doing- in their current state, but a lot of these buffs don't sound like a good idea. 

As a cargo tech there's plenty of ways to make money if you just chat with people or put effort into it.

- Mechs
- Woodcutting
- Glassworking (Admittedly, I hate this and it's semi-broken.)
- Botany Plants
- Mechs
- Bounties
- Organ Harvesting
- Crate Retrieval
- Selling Excess Materials from Mining

As for this PR specifically, I have a few things to point out.

Trashbags of holding can be bought in the advanced sanitation crate for ~7000 credits, giving a 6000 credit reward basically offsets the entire cost. It's also incredibly easy to get for any service member if someone just asks science or the AI to research sanitation tech.

The meat buffs, I feel, could be easily exploited. If biogens get upgraded they can basically print meat forever, and you get 21 credits each (compared to 50 for a burger, which is even more work.)

Pizzas shouldn't be 720 credits. You can make a custom pizza with basically anything and it only costs one dough.

The barrels and coffins I feel were fine as is. Yes, you get a low amount of money for them, but you can double your money on a towercap crate, and make -even more- by turning them into barrels or coffins. 

Buffing a lot of these materials is really questionable to me you already get a TON of money for them if a miner gives even the littlest shit.

Same goes for a lot of the statues, you can sell the materials for cash already, and you get a -bit- more for statues, you should not be getting such massive returns.

The weapons did need to see a buff, but I feel that the amount may be too high for them. That being said, I don't deal with security roles, so I don't know how rare or hard some of them are to get.

Handcuff price probably shouldn't be 30 unless it's specifically the security subtype, I think it uses any handcuffs with this, including cable cuffs.

2020-09-18 14:28 UTC, Investigator77 commented
Organ harvesting wasn't worthwhile at all. The reagent nerf killed botany's relation with cargo, the only time they're useful is when a botanist bothers to make chili plants that spawn gold and bluespace crystals on harvest. The entire point of the buff is that selling practically anything should be viable, it's a general flat-out buff to everything. Science can make maxcaps and use anomalies to max research 30 minutes in, sec has to do nothing for upgrades, engineering sets up the engines and either goes to do a project out of boredom or nothing the entire shift, each service role has a fun little gimmick, and so on. Pretty much every role has to do simple tasks to have their entire role completed, except cargo. Because of Citadel's "40 minute round with constant antag roll" the system was adjusted to kick supply in the nuts so that there's no issue when the revs that spawned kill the now-a-head QM before he's able to order anything against them.

This PR intends to make cargo a fun experience. You don't need to sit on your ass and beg other departments for anything, you can do your own thing and you'll always have enough cash to go around. The meta is no longer "Glassworking or mechs", the meta is anything and everything.

2020-09-18 19:29 UTC, Owai-Seek commented
The meta being "Everything and everything" literally just makes it so you don't -have- to do anything. Within the first 15 minutes you'll have enough cash to sit on your thumb and spin circles until you've drilled a new hole in yourself.

While playing cargo, I've consistently had my job taken from be from people literally just throwing money at the department, while there's nothing for -me- as the cargo tech to do. (Besides ordering a shitload of things for myself.)

Just drowning the department in money isn't going to make the gameplay loop feel any better.

2020-09-20 01:22 UTC, YakumoChen commented
I'll note like in the other PR about cargo that the point of the bicycle is to be able to tell when cargo is making too much money, to signal when cargo needs nerfed.

Cargo does not need buffs. It makes plenty of money and is perhaps one of the most directly powerful departments. Cargo can directly order guns and most supplies to make it entirely self-sufficient from the station (Cargonia is a meme for a good reason) and it really does not have trouble making money, especially if you're doing the bounties.

2020-09-20 01:55 UTC, YakumoChen commented
The reagent value buffs are kind of absurd. You can sell _water_ for a credit per unit. Most of the lesser values have been increased at least 10fold. I saw one testmerge round out of this and cargo had hundreds of thousands of credits after 2 hours, which is a **massive** red flag

2020-09-20 05:35 UTC, Investigator77 commented
> What does cargo need all these credits for anyway? I didn't see much except for cargo buying a bunch of joy-ride gear from their hoard. Cargo almost never supplies other departments with stuff voluntarily (something which is literally the goal and function of the department)

That's a player issue I can't rectify with a PR.
Anyway, I'm addressing some balance concerns.

2020-09-25 22:51 UTC, MLGTASTICa commented
Hey , so you buffed uncommon reagent cost value to 15 credits per unit. This leads to a blood crate (which has 9 bloodbags) costing 3000 credits , but being sell-able for 24000 credits. I guess this is test-merged since the normal value is 1 per reagent.

2020-09-26 10:28 UTC, Azarak commented
> 
> 
> Hey , so you buffed uncommon reagent cost value to 15 credits per unit. This leads to a blood crate (which has 9 bloodbags) costing 3000 credits , but being sell-able for 24000 credits. I guess this is test-merged since the normal value is 1 per reagent.

^

2020-09-26 10:34 UTC, ForrestWick commented
Reagent selling is too exploitable, hence why it was nerfed. Cargo should be about production tbh, which is why instead of regents you should be able to sell raw plants. You can already sell the seed packet for each plant once and make a decent amount off rarer ones, but the plants sell for shit because it's based off regents.

2020-09-26 10:35 UTC, ForrestWick commented
Also people downvoting owai despite him being completely correct. Just another day on slyrat

2020-09-26 10:40 UTC, Investigator77 commented
> Hey , so you buffed uncommon reagent cost value to 15 credits per unit. This leads to a blood crate (which has 9 bloodbags) costing 3000 credits , but being sell-able for 24000 credits. I guess this is test-merged since the normal value is 1 per reagent

Acknowledged when you posted it, haven't got around to it but I will address it very soon.

>Also people downvoting owai despite him being completely correct. Just another day on skyrat

Let's not start this in here please?

2020-09-26 10:43 UTC, ForrestWick commented
> > Hey , so you buffed uncommon reagent cost value to 15 credits per unit. This leads to a blood crate (which has 9 bloodbags) costing 3000 credits , but being sell-able for 24000 credits. I guess this is test-merged since the normal value is 1 per reagent
> 
> Acknowledged when you posted it, haven't got around to it but I will address it very soon.
> 
> >Also people downvoting owai despite him being completely correct. Just another day on skyrat
> 
> Let's not start this in here please?

No because this just reinforces my point I've made about 10 times now of skyrat development solely consisting of people going "dude itd be cool if we did this thing", not having any forward thinking put into the thing they do, and being surprised when it turned out to cause problems.

2020-09-26 12:33 UTC, Owai-Seek commented
![2jYCKZYlYG](https://user-images.githubusercontent.com/7543955/94340339-f3fcd380-ffce-11ea-9458-e90c8aaaed49.png)

So, this is a shift where I played cargo last night on deadpop. I bought ~16k in Meteor Shields,  and 12k  in stuff for Botany/Kitchen. The other Cargo Tech bought ~7k worth of carpet. There -was- however, a point where I demanded a budget card be used, which was 6000 credits cargo didn't have to spend.

That's 35k Spent on things people actually wanted. We had 56k left over with zero bounties done, nobody giving us money, and no materials sold. This was -just- from glassworking and woodcutting.  Even if the one budget card order was spent through cargo, we still had 50k

![0rP7BUHGux](https://user-images.githubusercontent.com/7543955/94340341-f6f7c400-ffce-11ea-9b6c-39c3b45d2907.png)

That's the amount of materials we had to sell from the single miner. Let's be -extremely-  cutthroat about it, and assume that a normal miner will only get ~50% of that, and you sell half, of the -best selling- items. without touching diamonds, because Science will hate you.

112 Silver x 80c = 8960
280 Plasma x 150c = 42000
125 Gold x 100c = 12500
185 Titanium x 60c = 11000
**Total Profits: 74460**

_Even -PRIOR- numbers were a lot._

112 Silver x 25c = 2800
280 Plasma x 100c =28000
125 Gold x 60c = 7500
185 Titanium x 60c = 11000
**Total Profits: 49300**

This nonsense doesn't even factor in outside variables. This is zero bounties done, nobody brought cargo anything to sell in that time, we didn't make a statue/barrel production line. This is straight up, just low skill production work without making anything fancy. The budget card request was for botany, because they had ordered 5 Exotic Seed Crates, and wanted 4 more.

I'd be fine with bounties seeing a buff. Nobody ever does them because there's easier ways to make money. As I said before, a lot of the time, people just HAND me money. Shaft Miners, Budget Cards, ect.

I'm seeing people get bicycles consistently, and as far as I'm aware, the bicycle is a meme. You're not -supposed- to be able to get it. People having it is generally a sign that something is fundamentally broken at cargo. Hell, I could have easily had one if I sold all the materials that shift.

2020-09-26 12:56 UTC, Azarak commented
Looking over it and how it plays out, Owai's right. The bumped export prices are way tooo much, I don't mind higher bounties as it actually encourages people to go out of their way to interact with something, or someone unique each shift, while the exports just incentivise people to find an exploit and profit off of that.

2020-09-26 12:57 UTC, Azarak requested changes
Revert the export rates

2020-09-26 12:58 UTC, ForrestWick commented
A lot of the export prices and rates can be buffed just a tiny bit, but aza is right in that they're too high rn

2020-10-25 00:38 UTC, closed without merging