Changes to Dinnerware Vendors on Boxstation and Cook starting amount of ingredients
Skyrat-SS13/Skyrat13 pull request #3582
Opened 2020-09-20 01:43 UTC by DuffCreeper

## About The Pull Request

Removes custom attributes to the Dinnerware Vendors in Kitchen and Brig Kitchen as they do not add anything new and prevent the Vendors from updating from the vendor modules if they were to change
The only thing that is being removed is flour from the Kitchen _'Contraband'_ which I made up for by adding two more bags of rice and flour to spawn on the table at round start

## Why It's Good For The Game

Allows changes made to the Dinnerware Vendors in modules to properly sync to Boxstation Dinnerware Vendors and for the Cook to have more ingredients at round start without needing to hack his own vendor to get access to 'contraband' flour

## Changelog
:cl:
Removed custom properties from Brig Kitchen and Cook's Kitchen Dinnerware vendor
Added two more bags of rice and flour to the Cook's Kitchen table at round start
/:cl:

2020-09-20 04:26 UTC, Owai-Seek commented
For a minute I was concerned, but I'm assuming these are var edited variants on the map, so it seems fine.

2020-09-20 04:46 UTC, DuffCreeper commented
> For a minute I was concerned, but I'm assuming these are var edited variants on the map, so it seems fine.

Nah haven't touched anything super serious, more or less just touched vending machines related to cooking so when ever someone touches the contents of them in modules, they properly get updated.

2020-09-20 06:12 UTC, Owai-Seek commented
Yeeep, var edited variants on maps are really annoying to deal with unless it's something super specific for one time use.

2020-09-25 05:50 UTC, KathrinBailey requested changes
Why are you putting code comments in a map file?
Also, you don't do this anyway. This is a modular file. You don't need to make a modularisation edit in a modular file.

2020-09-25 05:54 UTC, DuffCreeper commented
> Why are you putting code comments in a map file?
> Also, you don't do this anyway. This is a modular file. You don't need to make a modularisation edit in a modular file.

Wasn't quite sure if I had to or not honestly, so apologies for that

And regarding the file, wasn't quite sure how to go about that so I just did it like this I guess

2020-10-24 00:37 UTC, closed without merging